version: '3.8'

services:

  zookeeper:
    platform: linux/x86_64
    image: confluentinc/cp-zookeeper:7.7.1
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - kafka-network

  kafka:
    platform: linux/x86_64
    image: confluentinc/cp-kafka:7.7.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"  # Make sure Kafka is exposed on port 9092
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_SASL_ENABLED: 'false'
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Advertise Kafka broker on 9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_SERVER_PROPERTIES: |
        auto.create.topics.enable=true
        offsets.topic.replication.factor=1
      KAFKA_CREATE_TOPICS: test-topic:1:1
    networks:
      - kafka-network
  
  jobmanager:
    image: flink:1.16.0
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - kafka-network

  taskmanager:
    image: flink:1.16.0
    container_name: taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - kafka-network

  myapp:
    build: .
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092  # Use the correct Kafka port 9092
    networks:
      - kafka-network
    command: ["python", "job.py"]

networks:
  kafka-network:
