FROM alpine:3.17.0 AS builder

FROM apache/flink:1.16.2-scala_2.12-java8 AS runtime

# Install Python 3.8 & git & PyFlink
RUN apt-get update && apt-get install -y software-properties-common &&  \
    add-apt-repository -y ppa:deadsnakes/ppa &&  \
    apt-get remove -y software-properties-common && apt-get autoremove -y && apt-get clean
RUN apt-get update && apt-get install -y python3.8 python3-pip python3.8-distutils git && apt-get clean

RUN python3.8 -m pip install --upgrade pip && \
    python3.8 -m pip install apache-flink==1.16.2 --no-cache-dir

RUN ln -sf /usr/bin/python3.8 /usr/bin/python3

# คัดลอกไฟล์ job.py เข้า Container
COPY job.py /opt/flink/job.py
# COPY check_libs.py /opt/flink/check_libs.py

ENTRYPOINT ["python3", "/opt/flink/job.py"]
# ENTRYPOINT ["python3", "/opt/flink/check_libs.py"]